name: tag-and-release-draft

on:
  push:
    branches: ["main"]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
               
      - name: Set date
        id: date
        run: echo "date=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
        
      - name: Set commit count
        run: |
          echo "count=$(git log --oneline | wc -l)" >> $GITHUB_ENV
          
      - name: Create tag
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ''
          custom_tag: ${{ format('{0}-{1}', env.date, env.count ) }}
          
      - name: Create draft pre-release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ format('{0}-{1}', env.date, env.count ) }}
          draft: true
          prerelease: true
          generate_release_notes: true
